name: Notify documentation update

on:
  workflow_dispatch:
  # reduce notification update while the definitive process is not set
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: "Post to Frog #documentation"
        if: ${{ !env.ACT }} # skip during local actions testing
        id: slack-frog
        uses: slackapi/slack-github-action@v1.19.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'C04KCT00BJ4'
          # For posting a simple plain text message
          slack-message: "La documentation a été mise à jour (${{ job.status }})\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.GITBOOK_BOT_TOKEN }}
